export const metadata = {
  title: `${pageNumber} Access Workflow Errors`,
}

# {metadata.title}

In this chapter, you’ll learn how to access errors that occur during a workflow’s execution.

## How to Access Workflow Errors?

By default, when an error occurs in a workflow, it throws that error, and the execution stops.

You can configure the workflow to return the errors instead so that you can access and handle them differently.

For example:

export const highlights = [
  ["11", "errors", "`errors` is an array of errors that occur during the workflow's execution."],
  ["14", "throwOnError", "Specify that errors occuring during the workflow's execution should be returned, not thrown."],
]

```ts title="src/api/workflows/route.ts" highlights={highlights} collapsibleLines="1-6" expandButtonLabel="Show Imports"
import type {
  MedusaRequest,
  MedusaResponse,
} from "@medusajs/framework/http"
import myWorkflow from "../../../workflows/hello-world"

export async function GET(
  req: MedusaRequest,
  res: MedusaResponse
) {
  const { result, errors } = await myWorkflow(req.scope)
    .run({
	    // ...
      throwOnError: false,
    })

  if (errors.length) {
    return res.send({
      errors: errors.map((error) => error.error),
    })
  }

  res.send(result)
}

```

The object passed to the `run` method accepts a `throwOnError` property. When disabled, the errors are returned in the `errors` property of `run`'s output.

The value of `errors` is an array of error objects. Each object has an `error` property, whose value is the name or text of the thrown error.
